### ISSUE TITLE
Renaming "column" with ecto migrations only updates the "column" name in the first document

### ISSUE THREAD

**Issue by JamieREvans** [ankhers/mongodb_ecto#158]
Context: This was from the `ecto-2.1` branch.

I wrote a migration to rename a field, but when I run the migration, it only updates the first document.

``` elixir
rename table(:report), :old_name, to: :new_name
```

**Comment by ankhers** [comment]
Would you mind testing out whether the current master does what you are expecting?

**Comment by JamieREvans** [comment]
@ankhers When I update to the current master, the migration fails:

```
** (MatchError) no match of right hand side value: 15
    lib/mongo_ecto.ex:777: Mongo.Ecto.execute_ddl/3
    (ecto) lib/ecto/migration/runner.ex:98: anonymous fn/2 in Ecto.Migration.Runner.flush/0
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/migration/runner.ex:96: Ecto.Migration.Runner.flush/0
    (stdlib) timer.erl:181: :timer.tc/2
    (ecto) lib/ecto/migration/runner.ex:27: Ecto.Migration.Runner.run/6
    (ecto) lib/ecto/migrator.ex:127: Ecto.Migrator.attempt/6
    (ecto) lib/ecto/migrator.ex:73: anonymous fn/4 in Ecto.Migrator.do_up/4
```

**Comment by JamieREvans** [comment]
@ankhers I've opened a PR (#159) that will help with the above.

**Comment by JamieREvans** [comment]
Thanks @habutre. It seems that I didn't link the issue with the PR description.
