### ISSUE TITLE
function nil.__struct__/0 is undefined or private

### ISSUE THREAD

**Issue by diego-** [ankhers/mongodb_ecto#85]
Getting this error from a basic query:

```
query = from w in "design_search_codes",
    where: w.code == ^search_code,
    select: w
    result = Repo.all(query)

```

Relevant stack trace:

```
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function nil.__struct__/0 is undefined or private
        nil.__struct__()
        (ecto) Ecto.Schema.__load__/6
        (elixir) lib/enum.ex:1183: Enum."-map/2-lists^map/1-0-"/2
        (mongodb_ecto) lib/mongo_ecto.ex:428: anonymous fn/4 in Mongo.Ecto.execute/6
        (elixir) lib/enum.ex:1252: anonymous fn/3 in Enum.map_reduce/3
        (elixir) lib/enum.ex:1627: anonymous fn/3 in Enum.reduce/3
        (elixir) lib/enum.ex:2842: Enumerable.List.reduce/3
        (elixir) lib/stream.ex:1163: Stream.do_list_resource/6
        (elixir) lib/enum.ex:1626: Enum.reduce/3
        (elixir) lib/enum.ex:1250: Enum.map_reduce/3
        (mongodb_ecto) lib/mongo_ecto.ex:428: Mongo.Ecto.execute/6
        (ecto) lib/ecto/repo/queryable.ex:95: Ecto.Repo.Queryable.execute/5
        (ecto) lib/ecto/repo/queryable.ex:15: Ecto.Repo.Queryable.all/4

```

using elixir 1.3.0, mongodb_ecto 0.1.2, phoenix_ecto 2.0.2

**Comment by michalmuskala** [comment]
Could you try with the newest `mongodb_ecto` release?

**Comment by diego-** [comment]
still occurring with the latest release

**Comment by ankhers** [comment]
I am closing this for now as this is reported on a no longer maintained version of this adapter. Please re open or create another ticket if this is still happening on either the `ecto-2` or `ecto-2.1` branch.
